# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #m

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[40,)" #m	See our download page for lists of versions.

# The license for your mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="licensed under GPLv3."

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="Issue tracker WIP" #o

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="zombie1" #m

 # A display name for the mod
displayName="Zombie1" #m

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="Auto-Update WIP" #o

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="Display URL WIP" #o

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #o

# A text field displayed in the mod UI
credits="This mod was created solely by O, with strong inspiration from the popular Zombies game mode" #o

# A text field displayed in the mod UI
authors="O" #o

# The description text for the mod (multi line!) (#mandatory)
description='''
This Zombies-styled mod, while drawing a lot of inspiration, contains its own unique elements. These include: more zombie types, with more variety per rounds,
completely custom map creation, involving placable zombie spawn points and a method to get random weapons and armour.
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.zombie1]] #o
    # the modid of the dependency
    modId="forge" #m
    
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #m
    # The version range of the dependency
    versionRange="[40,)" #m
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
    
# Here's another dependency
[[dependencies.zombie1]]
    modId="minecraft"
    mandatory=true
    
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
